<?php
declare(strict_types=1);
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search companies
    </h1>
    <p>
        <?php echo $this->tag::linkTo(['admin/comments/new', 'Create comments']) ?>
    </p>
    <p>
        <?php echo $this->tag::linkTo(['admin/comments/list', 'List']) ?>
    </p>
    <p>
        <?= $this->tag::linkTo(['admin', 'Main ']); ?>
    </p>
</div>

<?php if (isset($_GET['notice'])) : ?>
    <div style="text-align: center;color:coral;"><?php echo urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="text-align: center;color:darkolivegreen;"><?php echo urldecode($_GET['success']); ?></div>
<?php endif; ?>

<?php echo $this->getContent() ?>

<?php
echo $this->tag::form(
    [
        'admin/comments/search',
        'autocomplete' => 'off',
        'class' => 'form-horizontal'
    ]
);
?>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['title', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldTitle']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldText" class="col-sm-2 control-label">Text</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textArea(['text', 'cols' => 30, 'rows' => 4, 'class' => 'form-control', 'id' => 'fieldText']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldArticles" class="col-sm-2 control-label">Article</label>
    <div class="col-sm-10">
        <?php echo $this->tag::select(
            [
                'article_id',
                \App\Model\Articles::find(),
                'using' => [
                    'id',
                    'name'
                ],
                'id' => 'fieldArticles'
            ]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUser" class="col-sm-2 control-label">User</label>
    <div class="col-sm-10">
        <?php echo $this->tag::select(
            [
                'user_id',
                \App\Model\Users::find(),
                'using' => [
                    'id',
                    'name'
                ],
                'id' => 'fieldUser'
            ]) ?>
    </div>
</div>


<div class="form-group">
    <label for="fieldComments" class="col-sm-2 control-label">Parent</label>
    <div class="col-sm-10">
        <?php echo $this->tag::select(
            [
                'article_id',
                \App\Model\Comments::find(),
                'using' => [
                    'id',
                    'title'
                ],
                'id' => 'fieldComments'
            ]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag::submitButton(['Search', 'class' => 'btn btn-default']) ?>
    </div>
</div>

<?php echo $this->tag::endForm(); ?>
