<?php
declare(strict_types=1);
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag::linkTo(['admin/partners/index', 'Go Back']); ?></li>
            <li class="next"><?php echo $this->tag::linkTo(['admin/partners/new', 'Create ']); ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin', 'Main ']); ?></li>
        </ul>
    </nav>
</div>


<div class="page-header">
    <h1>List Partners</h1>
</div>


<?php if (isset($_GET['notice'])) : ?>
    <div style="color:coral;text-align: center;"><?= urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="color:darkolivegreen;text-align: center;"><?= urldecode($_GET['success']); ?></div>
<?php endif; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Company</th>
            <th>Approved</th>
            <th>Level</th>
            <th>Description</th>
            <th>City</th>
            <th>Country</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Requisites</th>
            <th>Created</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $partner): ?>
            <tr>
                <td><?php echo $partner->id ?></td>
            <td><?php echo $partner->name ?></td>
            <td><?php echo $partner->company ?></td>
            <td><?php echo $partner->approved ?></td>
            <td><?php echo $partner->level ?></td>
            <td><?php echo $partner->description ?></td>
            <td><?php echo $partner->city ?></td>
            <td><?php echo $partner->country_id ?></td>
            <td><?php echo $partner->address ?></td>
            <td><?php echo $partner->phone ?></td>
            <td><?php echo $partner->email ?></td>
            <td><?php echo $partner->requisites ?></td>
            <td><?php echo $partner->created ?></td>

                <td><?php echo $this->tag::linkTo(['admin/partners/edit/' . $partner->id, 'Edit']); ?></td>
                <td><?php echo $this->tag::linkTo(['partners/delete/' . $partner->id, 'Delete']); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, '/', $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <?php if ($page->total_items > $page->limit) : ?>
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag::linkTo('admin/partners/list', 'First') ?></li>
                <li><?php echo $this->tag::linkTo('admin/partners/list?page=' . $page->before, 'Previous') ?></li>
                <li><?php echo $this->tag::linkTo('admin/partners/list?page=' . $page->next, 'Next') ?></li>
                <li><?php echo $this->tag::linkTo('admin/partners/list?page=' . $page->last, 'Last') ?></li>
            </ul>
        </nav>
        <?php endif; ?>
    </div>
</div>
