
<div style="width: 100%; text-align: center">ADMIN</div>
<ul>
    <li>
        <a href="/admin/articles/list">Articles</a>
    </li>
    <li>
        <a href="/admin/article_images/list">Article Images</a>
    </li>
    <li>
        <a href="/admin/companies/list">Companies</a>
    </li>
    <li>
        <a href="/admin/company_manager/list">Company Manager</a>
    </li>
    <li>
        <a href="/admin/countries/list">Countries</a>
    </li>
    <li>
        <a href="/admin/deals/list">Deals</a>
    </li>
    <li>
        <a href="/admin/education/list">Education</a>
    </li>
    <li>
        <a href="/admin/expert_info/list">Expert Info</a>
    </li>
    <li>
        <a href="/admin/images/list">Images</a>
    </li>
    <li>
        <a href="/admin/managers/list">Managers</a>
    </li>
    <li>
        <a href="/admin/payment_country/list">Payment Country</a>
    </li>
    <li>
        <a href="/admin/payment_user/list">Payment User</a>
    </li>
    <li>
        <a href="/admin/partners/list">Partners</a>
    </li>
    <li>
        <a href="/admin/payments/list">Payments</a>
    </li>
    <li>
        <a href="/admin/professional_experience/list">Professional Experience</a>
    </li>
    <li>
        <a href="/admin/resumes/list">Resumes</a>
    </li>
    <li>
        <a href="/admin/skills/list">Skills</a>
    </li>
    <li>
        <a href="/admin/subscriptions/list">Subscriptions</a>
    </li>
    <li>
        <a href="/admin/user_subscription/list">User Subscription</a>
    </li>
    <li>
        <a href="/admin/users/list">Users</a>
    </li>
    <li>
        <a href="/admin/vacancies/list">Vacancies</a>
    </li>
</ul>
<hr>
<br>
<br>
<ul>
    <li>
        <a href="/admin/user/list">User</a>
    </li>
    <li>
        <a href="/admin/company/list">Company</a>
    </li>
    <li>
        <a href="/admin/partner/list">Partner</a>
    </li>
    <li>
        <a href="/admin/vacancy/list">Vacancy</a>
    </li>
    <li>
        <a href="/admin/resume/list">Resume</a>
    </li>
</ul>
