<h3>Vacancies</h3>
<div style="width: 100%;margin-top: 50px;"><a href="/admin/vacancy/add" target="_blank" style="float: right"><button class="btn btn-success">Add new</button></a></div>
<table id="table_users" class="display compact" cellspacing="0" width="100%" style="margin-bottom: 100px;">
    <thead>
    <tr>
        <th style="text-transform: uppercase; text-align: center;">ID</th>
        <th style="text-transform: uppercase; text-align: center;">Name</th>
        <th style="text-transform: uppercase; text-align: center;">Salary</th>
    </tr>
    </thead>
    <tbody id="table_body">
    <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
    </tr>
    </tbody>
</table>
<div style="margin-top: 50px;"></div>
<h4>Response</h4>
<div id="response" style="margin-top: 50px; background-color: lightgrey; color:darkolivegreen"></div>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var api_token = '';
        var url = '/vacancies';
        var xhr = new XMLHttpRequest();
        xhr.onload = function() {
            if (this.readyState === 4) {
                if (this.status === 200) {
                    try {
                        console.log(this.response);
                        var response = JSON.parse(this.response);
                        var vacancies = response.vacancies;
                        $('#response').text(this.response);
                        if (vacancies) {
                            var html = '';
                            [].forEach.call(vacancies, function (vacancy) {
                                html += '<tr>' +
                                    '<td class="id">' + vacancy.id + '</td>' +
                                    '<td class="name"><a href="/admin/vacancy/edit/' + vacancy.id + '" target="_blank"> ' + vacancy.name + '</a></td>' +
                                    '<td class="surname"><a href="/admin/vacancy/edit/' + vacancy.id + '" target="_blank"> ' + vacancy.salary + '</a></td>' +
                                '</tr>'
                            });
                            $('#table_body').html(html);
                            $('#table_users').DataTable({
                                'info': false,
                                'searching': false,
                                'lengthChange': false,
                                'pageLength': 3,
                                'order': [[0, "asc"]],
                                oLanguage: {
                                    oPaginate: {
                                        sNext: '<i class="fa fa-chevron-right" ></i>',
                                        sPrevious: '<i class="fa fa-chevron-left" ></i>'
                                    }
                                }
                            });
//                            console.log(html);
                        }
                    } catch (e) {
                        console.log('error', e.message);
                    }
                } else {
                    console.log('error response', this.response);
                }
            }
        };
        xhr.open('GET', url, true);
        xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        xhr.send();
    });
</script>