
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Phalcon REST Boilerplate</title>
	<style>
		/*@import url(//fonts.googleapis.com/css?family=Lato:700);*/

		body {
			margin:0;
			font-family:'Lato', sans-serif;
			text-align:center;
			color: #999;
		}

		.welcome {
			width: 500px;
			height: 300px;
			position: absolute;
			left: 50%;
			top: 50%;
			margin-left: -250px;
			margin-top: -200px;
		}
	</style>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
</head>
<body>
<div class="welcome">
	<h3>Login</h3>
    <?php echo $form->html; ?>
</div>
</body>
</html>