
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon REST Boilerplate</title>
    <style>
        @import url(//fonts.googleapis.com/css?family=Lato:700);

        body {
            margin:0;
            font-family:'Lato', sans-serif;
            text-align:center;
            color: #999;
        }

        .welcome {
            width: 300px;
            height: 200px;
            position: absolute;
            left: 50%;
            top: 50%;
            margin-left: -150px;
            margin-top: -100px;
        }
    </style>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
</head>
<body>
<div class="welcome">
    <h3>Change Password</h3>
    <br>
    <?php if (count($messages) > 0) : ?>
        <div class="messages" style="margin-top: 50px;color: red;">
            <img src="/img/danger.png" width="30"/>
            <br>
            <?php foreach($messages as $message) : ?>
                <?php echo $message; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <br>
    <?php echo $form->html; ?>
</div>
</body>
</html>