<?php
declare(strict_types=1);
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search professional_experience
    </h1>
    <p>
        <?php echo $this->tag::linkTo(['admin/professional_experience/new', 'Create professional_experience']) ?>
    </p>
    <p>
        <?php echo $this->tag::linkTo(['admin/professional_experience/list', 'List']) ?>
    </p>
    <p>
        <?= $this->tag::linkTo(['admin', 'Main ']); ?>
    </p>
</div>

<?php if (isset($_GET['notice'])) : ?>
    <div style="text-align: center;color:coral;"><?php echo urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="text-align: center;color:darkolivegreen;"><?php echo urldecode($_GET['success']); ?></div>
<?php endif; ?>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag::form(
        [
            'admin/professional_experience/search',
            'autocomplete' => 'off',
            'class' => 'form-horizontal'
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['id', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldId']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['title', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldTitle']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['description', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldDescription']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserId" class="col-sm-2 control-label">User</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['user_id', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldUserId']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldOrganization" class="col-sm-2 control-label">Organization</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['organization', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldOrganization']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCountry" class="col-sm-2 control-label">Country</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['country', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldCountry']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSite" class="col-sm-2 control-label">Site</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['site', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldSite']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProfessionalArea" class="col-sm-2 control-label">Professional Of Area</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['professional_area', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldProfessionalArea']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPosition" class="col-sm-2 control-label">Position</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['position', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldPosition']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStart" class="col-sm-2 control-label">Start</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['start', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldStart']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFinish" class="col-sm-2 control-label">Finish</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['finish', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldFinish']) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag::submitButton(['Search', 'class' => 'btn btn-default']) ?>
    </div>
</div>

<?php echo $this->tag::endForm(); ?>
