<?php if (count($messages) > 0) : ?>
    <div class="messages m-t-50 red-color">
        <div class="row">
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                <img src="/assets/images/danger.png" class="pull-right" width="20"/>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <?php foreach($messages as $message) : ?>
                    <?php echo $message; ?>
                <br>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if (isset($image) &&!empty($image)) : ?>
<div style="margin-top: 50px; margin-bottom: 30px;">
    <?php echo $image; ?>
</div>
<?php endif; ?>
<?php echo $form->html; ?>
