<?php
declare(strict_types=1);
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search companies
    </h1>
    <p>
        <?php echo $this->tag::linkTo(['admin/companies/new', 'Create companies']) ?>
    </p>
    <p>
        <?php echo $this->tag::linkTo(['admin/companies/list', 'List']) ?>
    </p>
    <p>
        <?= $this->tag::linkTo(['admin', 'Main ']); ?>
    </p>
</div>

<?php if (isset($_GET['notice'])) : ?>
    <div style="text-align: center;color:coral;"><?php echo urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="text-align: center;color:darkolivegreen;"><?php echo urldecode($_GET['success']); ?></div>
<?php endif; ?>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag::form(
        [
            'admin/companies/search',
            'autocomplete' => 'off',
            'class' => 'form-horizontal'
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['id', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldId']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['name', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldName']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textArea(['description', 'cols' => 30, 'rows' => 4, 'class' => 'form-control', 'id' => 'fieldDescription']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textArea(['address', 'cols' => 30, 'rows' => 4, 'class' => 'form-control', 'id' => 'fieldAddress']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
        <?php echo $this->tag::selectStatic(
                [
                        'status',
                    [
                            'pending' => 'pending',
                        'canceled' => 'canceled',
                        'rejected' => 'rejected',
                        'confirmed' => 'confirmed'
                    ],
                    'class' => 'form-control',
                    'id' => 'fieldStatus'
                ]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhone" class="col-sm-2 control-label">Phone</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['phone', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldPhone']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['email', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldEmail']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCity" class="col-sm-2 control-label">City</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['city', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldCity']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCountry" class="col-sm-2 control-label">Country</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['country', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldCountry']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAvatar" class="col-sm-2 control-label">Avatar</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['avatar', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldAvatar']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldReg" class="col-sm-2 control-label">Reg</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['reg', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldReg']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSite" class="col-sm-2 control-label">Site</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['site', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldSite']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRequisites" class="col-sm-2 control-label">Requisites</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textArea(['requisites', 'cols' => 30, 'rows' => 4, 'class' => 'form-control', 'id' => 'fieldRequisites']) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag::submitButton(['Search', 'class' => 'btn btn-default']) ?>
    </div>
</div>

<?php echo $this->tag::endForm(); ?>
