<?php
declare(strict_types=1);


use Phalcon\Paginator\Adapter\Model as Paginator;
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var $page Paginator */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag::linkTo(['admin/companies/index', 'Go Back']); ?></li>
            <li class="next"><?php echo $this->tag::linkTo(['admin/companies/new', 'Create ']); ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin/companies/list', 'List ']); ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin', 'Main ']); ?></li>
        </ul>
    </nav>
</div>


<div class="page-header">
    <h1>Search result</h1>
</div>


<?php if (isset($_GET['notice'])) : ?>
    <div style="color:coral;text-align: center;"><?= urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="color:darkolivegreen;text-align: center;"><?= urldecode($_GET['success']); ?></div>
<?php endif; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Address</th>
            <th>Status</th>
            <th>Phone</th>
            <th>Email</th>
            <th>City</th>
            <th>Country</th>
            <th>Avatar</th>
            <th>Reg</th>
            <th>Site</th>
            <th>Requisites</th>
            <th>CreationDate</th>
            <th>ModifiedDate</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $companie): ?>
            <tr>
                <td><?php echo $companie->id ?></td>
            <td><?php echo $companie->name ?></td>
            <td><?php echo $companie->description ?></td>
            <td><?php echo $companie->address ?></td>
            <td><?php echo $companie->status ?></td>
            <td><?php echo $companie->phone ?></td>
            <td><?php echo $companie->email ?></td>
            <td><?php echo $companie->city ?></td>
            <td><?php echo $companie->country ?></td>
            <td><?php echo $companie->avatar ?></td>
            <td><?php echo $companie->reg ?></td>
            <td><?php echo $companie->site ?></td>
            <td><?php echo $companie->requisites ?></td>
            <td><?php echo $companie->creationDate ?></td>
            <td><?php echo $companie->modifiedDate ?></td>

                <td><?php echo $this->tag::linkTo(['admin/companies/edit/' . $companie->id, 'Edit']); ?></td>
                <td><?php echo $this->tag::linkTo(['admin/companies/delete/' . $companie->id, 'Delete']); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, '/', $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <?php if ($page->total_items > $page->limit) : ?>
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag::linkTo('admin/companies/search', 'First') ?></li>
                <li><?php echo $this->tag::linkTo('admin/companies/search?page=' . $page->before, 'Previous') ?></li>
                <li><?php echo $this->tag::linkTo('admin/companies/search?page=' . $page->next, 'Next') ?></li>
                <li><?php echo $this->tag::linkTo('admin/companies/search?page=' . $page->last, 'Last') ?></li>
            </ul>
        </nav>
        <?php endif; ?>
    </div>
</div>
