<?php
declare(strict_types=1);
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag::linkTo(['admin/deals', 'Back']) ?></li>
            <br>
            <li class="previous"><?php echo $this->tag::linkTo(['admin/deals/list', 'List']) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit deals
    </h1>
</div>

<?php if (isset($_GET['notice'])) : ?>
    <div style="text-align: center;color:coral;"><?php echo urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="text-align: center;color:darkolivegreen;"><?php echo urldecode($_GET['success']); ?></div>
<?php endif; ?>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag::form(
        [
            'admin/deals/save',
            'autocomplete' => 'off',
            'class' => 'form-horizontal'
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['id', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldId']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPartnerId" class="col-sm-2 control-label">Partner</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['partner_id', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldPartnerId']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserId" class="col-sm-2 control-label">User</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['user_id', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldUserId']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldVacancyId" class="col-sm-2 control-label">Vacancy</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['vacancy_id', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldVacancyId']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreated" class="col-sm-2 control-label">Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['created', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldCreated']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSuccess" class="col-sm-2 control-label">Success</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['success', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldSuccess']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textArea(['description', 'cols' => 30, 'rows' => 4, 'class' => 'form-control', 'id' => 'fieldDescription']) ?>
    </div>
</div>


<?php echo $this->tag::hiddenField(['id']) ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag::submitButton(['Save', 'class' => 'btn btn-default']) ?>
    </div>
</div>

<?php echo $this->tag::endForm(); ?>
