<?php
declare(strict_types=1);
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var array $page ->items */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag::linkTo(['admin/deals/index', 'Go Back']); ?></li>
            <li class="next"><?php echo $this->tag::linkTo(['admin/deals/new', 'Create ']); ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin', 'Main ']); ?></li>
        </ul>
    </nav>
</div>


<div class="page-header">
    <h1>List Deals</h1>
</div>


<?php if (isset($_GET['notice'])) : ?>
    <div style="color:coral;text-align: center;"><?= urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="color:darkolivegreen;text-align: center;"><?= urldecode($_GET['success']); ?></div>
<?php endif; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Partner</th>
            <th>User</th>
            <th>Vacancy</th>
            <th>Created</th>
            <th>Success</th>
            <th>Description</th>

            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $deal): ?>
            <tr>
                <td><?php echo $deal->id ?></td>
                <td><?php echo $deal->partner_id ?></td>
                <td><?php echo $deal->user_id ?></td>
                <td><?php echo $deal->vacancy_id ?></td>
                <td><?php echo $deal->created ?></td>
                <td><?php echo $deal->success ?></td>
                <td><?php echo $deal->description ?></td>

                <td><?php echo $this->tag::linkTo(['admin/deals/edit/' . $deal->id, 'Edit']); ?></td>
                <td><?php echo $this->tag::linkTo(['admin/deals/delete/' . $deal->id, 'Delete']); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, '/', $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <?php if ($page->total_items > $page->limit) : ?>
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag::linkTo('admin/deals/list', 'First') ?></li>
                <li><?php echo $this->tag::linkTo('admin/deals/list?page=' . $page->before, 'Previous') ?></li>
                <li><?php echo $this->tag::linkTo('admin/deals/list?page=' . $page->next, 'Next') ?></li>
                <li><?php echo $this->tag::linkTo('admin/deals/list?page=' . $page->last, 'Last') ?></li>
            </ul>
        </nav>
        <?php endif; ?>
    </div>
</div>
