<?php
declare(strict_types=1);

use Phalcon\Paginator\Adapter\Model as Paginator;

/** @var $page Paginator */
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?= $this->tag::linkTo(['admin/expert_info/index', 'Go Back']) ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin/expert_info/new', 'Create ']) ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin', 'Main ']) ?></li>
        </ul>
    </nav>
</div>


<div class="page-header">
    <h1>Search result</h1>
</div>


<?php if (isset($_GET['notice'])) : ?>
    <div style="text-align: center;color:coral;"><?= urldecode($_GET['notice']) ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="text-align: center;color:darkolivegreen;"><?= urldecode($_GET['success']) ?></div>
<?php endif; ?>

<?= $this->getContent() ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>User</th>
            <th>Level</th>
            <th>Skills</th>

            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $expert_info): ?>
            <tr>
                <td><?= $expert_info->id ?></td>
                <td><?= $expert_info->user_id ?></td>
                <td><?= $expert_info->level ?></td>
                <td><?= $expert_info->skills ?></td>

                <td><?= $this->tag::linkTo(['admin/expert_info/edit/' . $expert_info->id, 'Edit']) ?></td>
                <td><?= $this->tag::linkTo(['admin/expert_info/delete/' . $expert_info->id, 'Delete']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?= $page->current, '/', $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <?php if ($page->total_items > $page->limit) : ?>
            <nav>
                <ul class="pagination">
                    <li><?= $this->tag::linkTo('admin/expert_info/list', 'First') ?></li>
                    <li><?= $this->tag::linkTo('admin/expert_info/list?page=' . $page->before, 'Previous') ?></li>
                    <li><?= $this->tag::linkTo('admin/expert_info/list?page=' . $page->next, 'Next') ?></li>
                    <li><?= $this->tag::linkTo('admin/expert_info/list?page=' . $page->last, 'Last') ?></li>
                </ul>
            </nav>
        <?php endif; ?>
    </div>
</div>
