<?php
declare(strict_types=1);

use Phalcon\Mvc\View\Engine\Php;
use Phalcon\Paginator\Adapter\Model as Paginator;
use App\Model\Subcategory;

/**
 * @var Php $this
 */
/** @var $page Paginator */
/** @var $subcategory Subcategory */

/** @var array $items */
$items = $page->items;
?>


<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?= $this->tag::linkTo(['admin/subcategory/index', 'Go Back']) ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin/subcategory/new', 'Create ']) ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin/subcategory/list', 'List ']) ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin', 'Main ']) ?></li>
        </ul>
    </nav>
</div>


<div class="page-header">
    <h1>Search result</h1>
</div>


<?php if (isset($_GET['notice'])) : ?>
    <div style="color:coral;text-align: center;"><?= urldecode($_GET['notice']) ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="color:darkolivegreen;text-align: center;"><?= urldecode($_GET['success']) ?></div>
<?php endif; ?>


<?= $this->getContent() ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Description</th>
            <th>Text</th>
            <th>CreationDate</th>
            <th>ModifiedDate</th>

            <th></th>
            <th></th>
        </tr>
        </thead>
                <tbody>
        <?php foreach ($items as $subcategory): ?>
            <tr>
                <td><?= $subcategory->getId() ?></td>
                <td><?= $subcategory->getTitle() ?></td>
                <td><?= $subcategory->getDescription() ?></td>
                <td><?= $subcategory->getText() ?></td>
                <td><?= $subcategory->getCreationDate() ?></td>
                <td><?= $subcategory->getModifiedDate() ?></td>

                <td><?= $this->tag::linkTo(['admin/subcategory/edit/' . $subcategory->getId(), 'Edit']) ?></td>
                <td><?= $this->tag::linkTo(['admin/subcategory/delete/' . $subcategory->getId(), 'Delete']) ?></td>
            </tr>
        <?php endforeach; ?>
                </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?= $page->current, '/', $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <?php if ($page->total_items > $page->limit) : ?>
        <nav>
            <ul class="pagination">
                <li><?= $this->tag::linkTo('admin/subcategory/search', 'First') ?></li>
                <li><?= $this->tag::linkTo('admin/subcategory/search?page=' . $page->before, 'Previous') ?></li>
                <li><?= $this->tag::linkTo('admin/subcategory/search?page=' . $page->next, 'Next') ?></li>
                <li><?= $this->tag::linkTo('admin/subcategory/search?page=' . $page->last, 'Last') ?></li>
            </ul>
        </nav>
        <?php endif; ?>
    </div>
</div>
