<?php
declare(strict_types=1);

use Phalcon\Paginator\Adapter\Model as Paginator;

/** @var $page Paginator */
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag::linkTo(['admin/resumes/index', 'Go Back']); ?></li>
            <li class="next"><?php echo $this->tag::linkTo(['admin/resumes/new', 'Create ']); ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin/resumes/list', 'List ']); ?></li>
            <li class="next"><?= $this->tag::linkTo(['admin', 'Main ']); ?></li>
        </ul>
    </nav>
</div>


<div class="page-header">
    <h1>Search result</h1>
</div>


<?php if (isset($_GET['notice'])) : ?>
    <div style="color:coral;text-align: center;"><?= urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="color:darkolivegreen;text-align: center;"><?= urldecode($_GET['success']); ?></div>
<?php endif; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>User</th>
            <th>Position</th>
            <th>Professional Area</th>
            <th>Salary</th>
            <th>Work Place</th>
            <th>Key Skills</th>
            <th>Language</th>
            <th>About Of Me</th>
            <th>Certification</th>
            <th>CreationDate</th>
            <th>ModifiedDate</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $resume): ?>
            <tr>
                <td><?php echo $resume->id ?></td>
            <td><?php echo $resume->user_id ?></td>
            <td><?php echo $resume->position ?></td>
            <td><?php echo $resume->professional_area ?></td>
            <td><?php echo $resume->salary ?></td>
            <td><?php echo $resume->work_place ?></td>
            <td><?php echo $resume->key_skills ?></td>
            <td><?php echo $resume->language ?></td>
            <td><?php echo $resume->about_me ?></td>
            <td><?php echo $resume->certification ?></td>
            <td><?php echo $resume->creationDate ?></td>
            <td><?php echo $resume->modifiedDate ?></td>

                <td><?php echo $this->tag::linkTo(['admin/resumes/edit/' . $resume->id, 'Edit']); ?></td>
                <td><?php echo $this->tag::linkTo(['admin/resumes/delete/' . $resume->id, 'Delete']); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <?php if ($page->total_items > $page->limit) : ?>
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag::linkTo('admin/resumes/search', 'First') ?></li>
                <li><?php echo $this->tag::linkTo('admin/resumes/search?page=' . $page->before, 'Previous') ?></li>
                <li><?php echo $this->tag::linkTo('admin/resumes/search?page=' . $page->next, 'Next') ?></li>
                <li><?php echo $this->tag::linkTo('admin/resumes/search?page=' . $page->last, 'Last') ?></li>
            </ul>
        </nav>
        <?php endif; ?>
    </div>
</div>
