<?php
declare(strict_types=1);
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search images
    </h1>
    <p>
        <?php echo $this->tag::linkTo(['admin/images/new', 'Create images']) ?>
    </p>
    <p>
        <?php echo $this->tag::linkTo(['admin/images/list', 'List']) ?>
    </p>
    <p>
        <?= $this->tag::linkTo(['admin', 'Main ']); ?>
    </p>
</div>

<?php if (isset($_GET['notice'])) : ?>
    <div style="color:coral;text-align: center;"><?php echo urldecode($_GET['notice']); ?></div>
<?php endif; ?>
<?php if (isset($_GET['success'])) : ?>
    <div style="color:darkolivegreen;"><?php echo urldecode($_GET['success']); ?></div>
<?php endif; ?>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag::form(
        [
            'admin/images/search',
            'autocomplete' => 'off',
            'class' => 'form-horizontal'
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['id', 'type' => 'number', 'class' => 'form-control', 'id' => 'fieldId']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPath" class="col-sm-2 control-label">Path</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['path', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldPath']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFilename" class="col-sm-2 control-label">FileName</label>
    <div class="col-sm-10">
        <?php echo $this->tag::textField(['fileName', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldFilename']) ?>
    </div>
</div>




<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag::submitButton(['Search', 'class' => 'btn btn-default']) ?>
    </div>
</div>

<?php echo $this->tag::endForm(); ?>
