<html>
<head>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <script src="/js/jquery.min.js" ></script>
    <script src="/js/bootstrap.min.js" ></script>
    <script src="/js/jquery.dataTables.min.js"></script>
    <script src="/js/select2.min.js" ></script>
</head>
<body>
<div class="container">
    <div class="row  center-block" style="margin-top: 100px;">
        <div class="col-lg-2"></div>
        <div class="col-lg-6">
            <?= $this->getContent() ?>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>
</body>
</html>