
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon</title>
    <style>
        @import url(//fonts.googleapis.com/css?family=Lato:700);

        body {
            margin:0;
            font-family:'Lato', sans-serif;
            text-align:center;
            color: #999;
        }

        .welcome {
            width: 300px;
            height: 200px;
            position: absolute;
            left: 50%;
            top: 50%;
            margin-left: -150px;
            margin-top: -100px;
        }

        a, a:visited {
            text-decoration:none;
        }

        h1 {
            font-size: 32px;
            margin: 16px 0 0 0;
        }
    </style>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <script src="/js/jquery.min.js" ></script>
    <script src="/js/croppie.js"></script>
    <script src="/js/bootstrap.min.js" ></script>
    <script src="/js/jquery.dataTables.min.js"></script>
    <script src="/js/select2.min.js" ></script>
</head>
<body>
<center><h2>ADMIN</h2></center>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <?php echo $this->getContent(); ?>
        </div>
    </div>
</div>
</body>
</html>
